# Generated by Django 4.1.7 on 2023-03-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicle", name="City08",),
        migrations.RemoveField(model_name="vehicle", name="CurbWeight",),
        migrations.RemoveField(model_name="vehicle", name="MFRCode",),
        migrations.AddField(
            model_name="vehicle", name="AdjWeight", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="City08U", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="RangeHwyA", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="comb08", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="combE", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="combinedUF", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="cylinders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle", name="displ", field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transmission_type",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
