# Generated by Django 4.1.7 on 2023-03-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0002_remove_vehicle_city08_remove_vehicle_curbweight_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle", old_name="Highway08", new_name="Highway08U",
        ),
    ]
