# Generated by Django 4.1.7 on 2023-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0004_alter_vehicle_cylinders_alter_vehicle_displ"),
    ]

    operations = [
        migrations.AddField(
            model_name="libatteryweightings",
            name="BC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="libatteryweightings",
            name="CH4",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="libatteryweightings",
            name="OC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="libatteryweightings",
            name="PM10",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="libatteryweightings",
            name="PM2p5",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="libatteryweightings",
            name="SOx",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="BC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="CH4",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="OC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="PM10",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="PM2p5",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nimhbatteryweightings",
            name="SOx",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="BC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="CH4",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="ICE_conv",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="ICE_lw",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="OC",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="PM10",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="PM2p5",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleweightings",
            name="SOx",
            field=models.FloatField(default=0),
        ),
    ]
