# Generated by Django 4.1.7 on 2023-03-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0005_libatteryweightings_bc_libatteryweightings_ch4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libatteryweightings",
            name="Material_y",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="nimhbatteryweightings",
            name="Material_y",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicleweightings",
            name="Material_y",
            field=models.CharField(max_length=50),
        ),
    ]
