# Generated by Django 4.1.7 on 2023-03-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0006_alter_libatteryweightings_material_y_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grid_emissions", old_name="CH4r", new_name="CH4Rate",
        ),
        migrations.RenameField(
            model_name="grid_emissions", old_name="CO2Er", new_name="CO2Rate",
        ),
        migrations.RenameField(
            model_name="grid_emissions", old_name="CO2r", new_name="CO2eRate",
        ),
        migrations.RenameField(
            model_name="grid_emissions", old_name="N20r", new_name="N2ORate",
        ),
        migrations.RenameField(
            model_name="grid_emissions", old_name="NOXr", new_name="NOXRate",
        ),
        migrations.RenameField(
            model_name="grid_emissions", old_name="SO2r", new_name="SO2Rate",
        ),
        migrations.RenameField(
            model_name="zip_region", old_name="region1", new_name="Subregion1",
        ),
        migrations.RenameField(
            model_name="zip_region", old_name="region2", new_name="Subregion2",
        ),
        migrations.RenameField(
            model_name="zip_region", old_name="region3", new_name="Subregion3",
        ),
        migrations.RemoveField(model_name="grid_emissions", name="state",),
    ]
