# Generated by Django 4.1.7 on 2023-03-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eeeApp", "0007_rename_ch4r_grid_emissions_ch4rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zip_region", old_name="state", new_name="State",
        ),
    ]
